server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/

spring:
  application:
    name: api-gateway

  cloud:
    gateway:

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes[0]:
        id: users-status-check
        uri: lb://users-ws # lb (load balancer)
        predicates:
          - Path=/users/status/check
          - Method=GET
        filters:
          - RemoveRequestHeader=Cookie
          - RewritePath=/users-ws(?<segment>/?.*), /$\{segment}

      routes[1]:
        id: users-ws
        uri: lb://users-ws # lb (load balancer)
        predicates:
          - Path=/users-ws/users
          - Method=POST
        filters:
          - RemoveRequestHeader=Cookie
          - RewritePath=/users-ws(?<segment>/?.*), /$\{segment}

      routes[2]:
        id: users-ws-login
        uri: lb://users-ws # lb (load balancer)
        predicates:
          - Path=/users-ws/users/login
          - Method=POST
        filters:
          - RemoveRequestHeader=Cookie
          - RewritePath=/users-ws(?<segment>/?.*), /$\{segment}




