spring:
  application:
    name: "configserver"


  profiles:
    # active: native
    active: git

  cloud:
    config:
      server:
        # native:
          # searchLocations: "file:///home/cristian/Documents/config"
          # searchLocations: "classpath:/config"
        git:
          uri: "https://github.com/CristianLopez3/microservices-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

server:
  port: 8071
