spring:
  application:
    name: "configserver"

  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: "file:///home/cristian/Documents/config"

          # searchLocations: "classpath:/config"
server:
  port: 8071
