spring:
  application:
    name: accounts

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  devtools:
    livereload:
      enabled: true

server:
  port: 8082

build:
  version: "1.0"

accounts:
  message: "Welcome to eazyback accounts related local APIS"
  contactDetails:
    name: "John Doe"
    email: "john@email.com"
  onCallSupport:
    -(555) 342 323
    -(555) 342 324


