spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "2.0"

accounts:
  message: "Welcome to eazyback accounts related local APIS from our production"
  contactDetails:
    name: "Daniel DDoe - Product Owner"
    email: "john@email.com"
  onCallSupport:
    -(555) 342 323
    -(555) 342 324
