springdoc:
  swagger-ui.path: /swagger-ui.html
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  paths-to-match: /**

server:
  error:
    include-message: always
    include-binding-errors: always