build:
  version: "2.0"

accounts:
  message: "Welcome to eazyback accounts related local APIS from our production"
  contactDetails:
    name: "Daniel Doe - Product Owner"
    email: "john@email.com"
  onCallSupport:
    - (555) 342 323
    - (555) 342 324
